'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';
import type { AnimeCard, SchedulePayload } from '../lib/types';
import { Bell, CalendarDays, Clock } from 'lucide-react';
const order=['senin','selasa','rabu','kamis','jumat','sabtu','minggu'];
function norm(d:string){return d.toLowerCase().replace(/[^a-z]/g,'')}
function estimate(i:number){return `${String(18 + (i%5)).padStart(2,'0')}:${i%2?'30':'00'} WIB`}
function saveReminder(day:string,item:AnimeCard,time:string){const old=JSON.parse(localStorage.getItem('animesu:reminders')||'[]');const reminder={id:`${item.slug}-${day}`,day,time,title:item.title,slug:item.slug,at:Date.now()};const next=[reminder,...old.filter((x:any)=>x.id!==reminder.id)].slice(0,80);localStorage.setItem('animesu:reminders',JSON.stringify(next)); if('Notification'in window){Notification.requestPermission().then(p=>{if(p==='granted') new Notification('Reminder Animesu aktif',{body:`${item.title} • ${day} ${time}`,icon:'/animesu-logo-192.png'})})} alert('Reminder disimpan di perangkat ini.');}
export function ScheduleCalendar({schedule,donghua}:{schedule:SchedulePayload;donghua?:SchedulePayload}){const days=useMemo(()=>{const map=new Map<string,AnimeCard[]>(); for(const s of [schedule,donghua].filter(Boolean) as SchedulePayload[]) for(const d of s.days||[]){const key=d.day||'Hari'; map.set(key,[...(map.get(key)||[]),...(d.items||[])]);} const arr=Array.from(map.entries()).map(([day,items])=>({day,items})); return arr.sort((a,b)=>order.indexOf(norm(a.day))-order.indexOf(norm(b.day)))},[schedule,donghua]); const todayName=new Intl.DateTimeFormat('id-ID',{weekday:'long'}).format(new Date()); const [active,setActive]=useState(days.find(d=>norm(d.day)===norm(todayName))?.day||days[0]?.day||''); const current=days.find(d=>d.day===active)||days[0]; return <section className="schedule-calendar"><div className="day-tabs" role="tablist" aria-label="Jadwal anime per hari">{days.map(d=><button key={d.day} className={d.day===active?'active':''} onClick={()=>setActive(d.day)} role="tab" aria-selected={d.day===active}>{d.day}<small>{d.items.length}</small></button>)}</div>{current?<div className="schedule-list">{current.items.map((a,i)=>{const time=estimate(i);return <article className="schedule-item" key={`${a.slug}-${i}`}><div className="schedule-time"><Clock size={16}/><b>{time}</b><span>{a.status||'Airing'}</span></div><div className="schedule-main"><h3>{a.title}</h3><p>Episode {a.episode||'terbaru'} • Subtitle Indonesia</p><div className="server-list"><Link className="btn secondary" href={`/anime/${a.slug}`}><CalendarDays size={16}/> Detail</Link><button className="btn" onClick={()=>saveReminder(current.day,a,time)}><Bell size={16}/> Reminder</button></div></div></article>})}</div>:<div className="panel muted">Jadwal belum tersedia.</div>}</section>}
